### ISSUE TITLE
Compile correctly with Kotlin 1.2

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.gradle#6]
```kotlin
System.err.writer().use { it.write("") }
```

```
'use((T) -> R): R' is only available since Kotlin 1.2 and cannot be used in Kotlin 1.1.
Requires newer compiler version to be inlined correctly.
```

**Comment by ericytsang** [comment]
I ran into the same problem.
After updating the Gradle version from 4.4.1 to 4.7, everything worked fine.

in `https://github.com/TWiStErRob/net.twisterrob.gradle/blob/master/gradle/wrapper/gradle-wrapper.properties`, replace the last line with:
```distributionUrl=https\://services.gradle.org/distributions/gradle-4.7-all.zip```

**Comment by TWiStErRob** [comment]
@ericytsang nice, thank you!

**Comment by MathieuLorber** [comment]
An update of the Gradle Kotlin plugin may help too =) (https://stackoverflow.com/questions/50053361/using-kotlin-version-1-2-but-still-get-compiler-error-about-use/53152730)

**Comment by TWiStErRob** [comment]
I haven't seen this warning in a while, but I have a hunch that something may be wrong with my setup as I may not be in control of which version Gradle is using to compile.
